export const basicMaterials = [
    {
        title:'配置规则',
        icon:'',
        value:'0',
        route:'configRule'
    },
    {
        title:'调度平台',
        icon:'',
        value:'1',
        children:[
            {
                title:'二级菜单1',
                icon:'',
                value:'1-0',
                route:'plant1'
            },
            {
                title:'二级菜单2',
                icon:'',
                value:'1-1',
                children:[
                    {
                        title:'三级菜单1',
                        icon:'',
                        value:'1-0',
                        route:'plant1-1'
                    },
                    {
                        title:'三级菜单2',
                        icon:'',
                        value:'1-1',
                        route:'plant1-2'
                    }
                ]
            },
        ]
    }
]
export const basicNavList = {
    logo:{
        src:'https://assets.le5lecdn.com/2d/img/logo.png',
        height:40,
        alt:'logo'
    },
    defaults:[{
        title:'二级菜单2',
        icon:'',
        value:'1-1',
        children:[
            {
                title:'三级菜单1',
                icon:'',
                value:'1-0-1',
                route:'plant1-1',
                children:[
                    {
                        title:'三级菜单1',
                        icon:'',
                        value:'1-0-1-1',
                        route:'plant1-1'
                    },
                    {
                        title:'三级菜单2',
                        icon:'',
                        value:'1-1-1-1',
                        route:'plant1-2'
                    }
                ]
            },
            {
                title:'三级菜单2',
                icon:'',
                value:'1-1-1',
                route:'plant1-2',
            }
        ]
    },],
    operations:[]
}